### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by bigfatbrowncat** [ibcn-cloudlet/dianne#4] opened 2016-07-07 07:03 UTC
I can't run dianne under windows after successful compilation. Here is the error log:

```
mnist:
     [echo] Launching DIANNE MNIST demo
   [delete] Deleting directory C:\mm\msys\home\imizus\Projects\dianne\tools\resources
    [mkdir] Created dir: C:\mm\msys\home\imizus\Projects\dianne\tools\resources
     [copy] Copying 5 files to C:\mm\msys\home\imizus\Projects\dianne\tools\resources
     [java] [MGMT-0]! Unexpected error in the run body: Illegal attribute name ";java.vm.version="25.92-b14";org.osgi.supports.framework.fragment="true";user.variant="";be.iminds.iot.dianne.dataset.mnist.location="datasets/MNIST/";be.iminds.iot.dianne.dataset.cifar100.location="datasets/CIFAR-100/";java.awt.printerjob="sun.awt.windows.WPrinterJob";sun.io.unicode.encoding="UnicodeLittle";org.osgi.framework.version="1.5.0";org.osgi.framework.storage="C:\mm\msys\home\imizus\Projects\dianne\tools\generated\[MGMT-0]";awt.toolkit="sun.awt.windows.WToolkit";org.osgi.framework.bundle.parent="boot";user.script="";org.osgi.supports.bootclasspath.extension="false";user.home="C:\Users\imizus";java.specification.vendor="Oracle Corporation";java.library.path="c:\Program Files\Java\jdk1.8.0_92\jre\bin
     [java] [MGMT-0]java.lang.NullPointerException
     [java] [MGMT-0]    at aQute.launcher.Launcher.deactivate(Launcher.java:716)
     [java] [MGMT-0]    at aQute.launcher.Launcher.run(Launcher.java:287)
     [java] [MGMT-0]    at aQute.launcher.Launcher.main(Launcher.java:87)
     [java] [MGMT-0]Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
     [java] [MGMT-0]-----------------
     [java] [MGMT-0]Errors
     [java] [MGMT-0]000: Exit code remote process 127: java -cp C:\Users\imizus\.bnd\cache\http%3A%2F%2Faiolos.intec.ugent.be%2Frepositories%2Fconcierge%2Forg.eclipse.concierge\org.eclipse.concierge-6.0.0.jar;C:\mm\msys\home\imizus\Projects\dianne\cnf\cache\biz.aQute.launcher\biz.aQute.launcher-latest.jar -Dlauncher.properties="C:\mm\msys\home\imizus\Projects\dianne\tools\generated\launch4352201364622373301.properties" aQute.launcher.Launcher
     [java] [MGMT-0]Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
     [java] 10:00:04 ERROR - Failed to launch
     [java] java.util.concurrent.TimeoutException: null
     [java]     at be.iminds.aiolos.cloud.local.CloudManagerLocal.startVMs(CloudManagerLocal.java:88) ~[na:na]
     [java]     at be.iminds.aiolos.cloud.local.CloudManagerLocal.startVM(CloudManagerLocal.java:69) ~[na:na]
     [java]     at be.iminds.aiolos.launch.CloudLauncher.launch(CloudLauncher.java:58) ~[be.iminds.aiolos.launch-0.6.0.jar:na]
     [java]     at be.iminds.aiolos.launch.Activator.start(Activator.java:72) [be.iminds.aiolos.launch-0.6.0.jar:na]
     [java]     at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645) [org.apache.felix.framework-4.2.1.jar:na]
     [java]     at org.apache.felix.framework.Felix.activateBundle(Felix.java:2146) [org.apache.felix.framework-4.2.1.jar:na]
     [java]     at org.apache.felix.framework.Felix.startBundle(Felix.java:2064) [org.apache.felix.framework-4.2.1.jar:na]
     [java]     at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955) [org.apache.felix.framework-4.2.1.jar:na]
     [java]     at aQute.launcher.Launcher.update(Launcher.java:436) [biz.aQute.launcher-latest.jar:na]
     [java]     at aQute.launcher.Launcher.activate(Launcher.java:349) [biz.aQute.launcher-latest.jar:na]
     [java]     at aQute.launcher.Launcher.run(Launcher.java:238) [biz.aQute.launcher-latest.jar:na]
     [java]     at aQute.launcher.Launcher.main(Launcher.java:87) [biz.aQute.launcher-latest.jar:na]
```

Could you give me a tip?

**Comment by tverbele** [comment] 2016-07-07 07:39
Currently Windows OS is not supported, only Linux and Mac OS X. Since none of the developers is actually using a Windows machine, it is also hard to reproduce this. Furthermore, in the upcoming 0.4 version the build and launch system will be completely overhauled, moving from ant to gradle.

My advice would be to install Ubuntu 14.04, on which DIANNE is tested the most.

**Comment by nicojanssens** [comment] 2016-07-07 08:47
@tverbele It may be useful to have a Dockerfile for bootstrapping DIANNE on other platforms as well. I'll have a look this evening and try to quickly hack something together.

**Comment by eliasdc** [comment] 2016-07-07 11:01
Added wontfix label because we have dependencies which are not able to be compiled on Windows (Torch7, cutorch). We won't be making any effort to support Windows until all dependencies support this.

A Dockerfile to bootstrap DIANNE is a good idea. Please keep us posted on the progress and problems.

**Comment by bigfatbrowncat** [comment] 2016-07-08 23:57
As far as I know, Torch7 could be built on Windows using mingw-w64 + MSYS

Anyway, if you aren't going to support this, it's your decision :) Thank you.

**Closed as completed** 2017-07-13 10:00 UTC
Labels: wontfix
